# NAME: Clayton Green, Anthony Humay
# EMAIL: clayton.green26@gmail.com, ahumay@ucla.edu
# ID: 404546151, 304731856

.SILENT:

default:
	rm -rf lab3b
	chmod u+x lab3b.sh
	ln lab3b.sh lab3b
	chmod u+x lab3b
	echo "Compilation finished"

clean:
	rm -rf *.tar.gz *.csv lab3b

dist:
	tar -czf lab3b-404546151.tar.gz lab3b.py lab3b.sh Makefile README