#NAME: Anthony Humay
#EMAIL: ahumay@ucla.edu
#ID: 304731856

default:
	tar -czf lab4a-304731856.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile 

.SILENT:

clean:
	rm -rf lab4a *.o *.tar.gz; \
	rm -rf *.txt 

dist:
	tar -czf lab4a-304731856.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile 
